/* Declarative settings config — add a SettingDef (and optional category)
   to grow the inspector. UI is generated by render.js; do not hand-build rows. */

import { getStyleSegmentOptions } from './styles.js';
import { scaledSliderSetting } from '../scale.js';
import {
  CURSOR_MODE_DEFAULT,
  CURSOR_MODE_OPTIONS,
} from '../../pixel-engine/cursor-mode.js';
import {
  PERFORMANCE_DEFAULTS,
  FRAME_RATE_OPTIONS,
  PIXEL_DENSITY_MIN,
  PIXEL_DENSITY_MAX,
} from '../../pixel-engine/performance-manager.js';
import {
  getBuiltinPresetOptions,
  PRESET_CUSTOM_ID,
} from '../presets/index.js';

/**
 * @typedef {'segment' | 'rgb' | 'slider' | 'dropdown' | 'toggle' | 'color' | 'number' | 'button'} SettingType
 *
 * @typedef {object} SettingDef
 * @property {string} id
 * @property {string} label
 * @property {string} [desc]
 * @property {string} categoryId — matches a SETTINGS_CATEGORIES entry
 * @property {string} [sectionId] — optional nested section within the category
 * @property {string} [styleId] — when set, only shown while that Pixel FS style is active
 * @property {SettingType} type
 * @property {*} [defaultValue]
 * @property {Array<{ value: string, label: string, disabled?: boolean }>} [options]
 * @property {() => Array<{ value: string, label: string, disabled?: boolean }>} [optionsFrom]
 *   — optional; may receive the settings api when used by render.js
 * @property {{ min: number, max: number, step?: number, unit?: string }} [range]
 * @property {object} [scale] — optional UI↔engine conversion from createUiScale / scaledSliderSetting
 * @property {boolean} [metaRow] — e.g. RGB swatch beside the label
 * @property {(api: object) => *} get
 * @property {(api: object, value: *, extra?: *) => void} set
 * @property {(api: object) => boolean} [disabledWhen]
 * @property {(api: object, selectable: string[]) => *} [resolveValue] — sync-time value coercion
 * @property {boolean} [syncOnSoft] — also refresh on soft AnimConfigChange (e.g. Preset → Custom)
 *
 * @typedef {object} SettingsSectionDef
 * @property {string} id — matched by SettingDef.sectionId within the parent category
 * @property {string} title
 * @property {boolean} [defaultOpen]
 * @property {string} [styleId] — when set, the whole nested section hides unless that style is active
 * @property {string} [emptyMessage]
 *
 * @typedef {object} SettingsCategoryDef
 * @property {string} id
 * @property {string} title
 * @property {boolean} [defaultOpen]
 * @property {string} [emptyMessage]
 * @property {SettingsSectionDef[]} [sections] — nested collapsible groups (e.g. Heat under Pixel Behavior)
 */

/** Placeholder copy for categories with no settings yet. */
export const EMPTY_SETTINGS_MESSAGE = 'No settings available yet';

/**
 * Ordered inspector categories. Future Pixel FS features land here by id;
 * leave settings arrays empty until controls exist.
 *
 * Pixel Behavior = physical properties of the Pixel FS (how pixels react,
 * move, how disturbances spread, how energy dissipates). Style-specific
 * brush knobs nest under `sections` (e.g. Heat). Visual Effects only choose
 * the disturbance type and shared appearance.
 *
 * @type {SettingsCategoryDef[]}
 */
export const SETTINGS_CATEGORIES = [
  {
    id: 'presets',
    title: 'Preset',
    defaultOpen: true,
  },
  {
    id: 'pixel-behavior',
    title: 'Pixel Behavior',
    defaultOpen: false,
    sections: [
      {
        id: 'heat',
        title: 'Heat',
        defaultOpen: true,
        styleId: 'heat',
      },
    ],
  },
  {
    id: 'visual-effects',
    title: 'Visual Effects',
    defaultOpen: true,
  },
  {
    id: 'animations',
    title: 'Animations',
    defaultOpen: true,
  },
  {
    id: 'cursor-interaction',
    title: 'Cursor Interaction',
    defaultOpen: false,
  },
  {
    id: 'performance',
    title: 'Performance',
    defaultOpen: false,
  },
];

/**
 * All inspector controls. Assign `categoryId` (and optional `sectionId`) to
 * place a control; optional `styleId` scopes it to an active Pixel FS style.
 *
 * Category-root settings (no sectionId) are for shared pixel physics /
 * interaction knobs. Style-specific behavior lives in nested sections.
 *
 * @type {SettingDef[]}
 */
export const SETTINGS = [
  /* Preset — top of the inspector. Every named preset (including Default)
     loads through the same transition pipeline. Custom is not selectable as a
     target: it appears when live settings no longer match a loaded built-in.
     Soft edits must refresh this row (syncOnSoft). */
  {
    id: 'pixel-preset',
    label: 'Preset',
    desc: 'Complete Pixel FS experience — refresh transition applies the load',
    categoryId: 'presets',
    type: 'dropdown',
    defaultValue: 'default',
    syncOnSoft: true,
    disabledWhen: (api) =>
      (typeof api.isPresetSystemActive === 'function' &&
        !api.isPresetSystemActive()) ||
      (typeof api.isPresetTransitionActive === 'function' &&
        api.isPresetTransitionActive()) ||
      (typeof api.isPixelDensityLocked === 'function' &&
        api.isPixelDensityLocked()),
    optionsFrom: (api) => {
      const opts =
        api && typeof api.getPresetOptions === 'function'
          ? api.getPresetOptions()
          : getBuiltinPresetOptions();
      /* Built-ins first (Default included), Custom last for display only —
         set() ignores Custom so it never overwrites a built-in definition. */
      return [
        ...opts,
        { value: PRESET_CUSTOM_ID, label: 'Custom' },
      ];
    },
    get: (api) => {
      if (typeof api.getActivePresetId === 'function') {
        return api.getActivePresetId() || PRESET_CUSTOM_ID;
      }
      return PRESET_CUSTOM_ID;
    },
    set: (api, value) => {
      if (!value || value === PRESET_CUSTOM_ID) return;
      if (
        typeof api.isPresetSystemActive === 'function' &&
        !api.isPresetSystemActive()
      ) {
        return;
      }
      if (
        typeof api.isPresetTransitionActive === 'function' &&
        api.isPresetTransitionActive()
      ) {
        return;
      }
      if (typeof api.loadPreset === 'function') api.loadPreset(value);
    },
  },
  /* Shared Pixel Behavior — category root; UI 0–10, engine native ranges.
     Physical properties of the Pixel FS. Future knobs (gravity, friction,
     turbulence, …) join this group; modes interpret them per energy model. */
  scaledSliderSetting(
    {
      id: 'pixel-reaction-strength',
      label: 'Pixel Reaction Strength',
      desc: 'How strongly pixels react to disturbances in the field',
      categoryId: 'pixel-behavior',
    },
    {
      get: (api) => api.getPixelReactionStrength(),
      set: (api, value) => api.setPixelReactionStrength(value),
      internal: { min: 0, max: 0.8, default: 0.4 },
    },
  ),
  scaledSliderSetting(
    {
      id: 'pixel-movement-speed',
      label: 'Pixel Movement Speed',
      desc: 'How quickly pixels move when reacting to a disturbance',
      categoryId: 'pixel-behavior',
    },
    {
      get: (api) => api.getPixelMovementSpeed(),
      set: (api, value) => api.setPixelMovementSpeed(value),
      internal: { min: 0.005, max: 0.2, default: 0.078 },
    },
  ),
  scaledSliderSetting(
    {
      id: 'pixel-decay-speed',
      label: 'Decay Speed',
      desc: 'How quickly energy introduced into the Pixel FS dissipates',
      categoryId: 'pixel-behavior',
    },
    {
      get: (api) => api.getPixelDecaySpeed(),
      set: (api, value) => api.setPixelDecaySpeed(value),
      internal: { min: 0.001, max: 0.1, default: 0.018 },
    },
  ),
  scaledSliderSetting(
    {
      id: 'pixel-trail-lifetime',
      label: 'Pixel Trail Lifetime',
      desc: 'How long residual motion trails persist after a disturbance',
      categoryId: 'pixel-behavior',
    },
    {
      get: (api) => api.getPixelTrailLifetime(),
      set: (api, value) => api.setPixelTrailLifetime(value),
      internal: { min: 0.85, max: 0.995, default: 0.965 },
    },
  ),
  /* Heat knobs — nested under Pixel Behavior → Heat; UI 0–10, engine native ranges. */
  scaledSliderSetting(
    {
      id: 'heat-intensity',
      label: 'Heat Intensity',
      desc: 'How strongly pixels react to heat',
      categoryId: 'pixel-behavior',
      sectionId: 'heat',
      styleId: 'heat',
    },
    {
      get: (api) => api.getHeatIntensity(),
      set: (api, value) => api.setHeatIntensity(value),
      internal: { min: 0, max: 1, default: 0.92 },
    },
  ),
  scaledSliderSetting(
    {
      id: 'heat-radius',
      label: 'Heat Radius',
      desc: 'Area around the cursor affected by heat',
      categoryId: 'pixel-behavior',
      sectionId: 'heat',
      styleId: 'heat',
    },
    {
      get: (api) => api.getHeatRadius(),
      set: (api, value) => api.setHeatRadius(value),
      internal: { min: 1, max: 30, default: 11.8 },
    },
  ),
  {
    id: 'style',
    label: 'Style',
    desc: 'Pixel field style',
    categoryId: 'visual-effects',
    type: 'segment',
    defaultValue: 'heat',
    optionsFrom: getStyleSegmentOptions,
    get: (api) => api.getBgMode(),
    set: (api, value) => {
      if (!api.getMotion()) return;
      api.setBgMode(value);
    },
    disabledWhen: (api) => !api.getMotion(),
    resolveValue: (api, selectable) => {
      const mode = api.getBgMode();
      if (selectable.indexOf(mode) !== -1) return mode;
      return api.getLastImplementedBgMode();
    },
  },
  {
    id: 'global-color',
    label: 'Global Color',
    desc: 'Shared by Heat, Wave, and Lightning',
    categoryId: 'visual-effects',
    type: 'rgb',
    defaultValue: { r: 255, g: 52, b: 158 },
    metaRow: true,
    get: (api) => api.getEffectColor(),
    set: (api, rgb, publish) => api.setEffectColor(rgb.r, rgb.g, rgb.b, publish),
  },
  /* Replaces the old Motion on/off pair: switching the pixel field off now
     hands that space to the inspector instead of leaving it blank. The panel
     opens inside whichever screen is in view and restores motion on close. */
  {
    id: 'settings-surface',
    label: 'Full Screen Settings',
    desc: 'Turn the pixel field into a full size settings panel',
    categoryId: 'animations',
    type: 'button',
    get: (api) =>
      typeof api.isSettingsExpanded === 'function' && api.isSettingsExpanded()
        ? 'Close'
        : 'Open',
    set: (api) => {
      if (typeof api.isSettingsExpanded !== 'function') return;
      if (api.isSettingsExpanded()) api.collapseSettings();
      else api.expandSettings();
    },
    disabledWhen: (api) => typeof api.expandSettings !== 'function',
  },
  {
    id: 'cursor-mode',
    label: 'Cursor Mode',
    desc: 'How the cursor interacts with the active Pixel FS style',
    categoryId: 'cursor-interaction',
    type: 'dropdown',
    defaultValue: CURSOR_MODE_DEFAULT,
    options: CURSOR_MODE_OPTIONS.slice(),
    get: (api) => api.getCursorMode(),
    set: (api, value) => api.setCursorMode(value),
  },
  /* Performance — density, quality, FPS, adaptive. Defaults preserve V1 look. */
  {
    id: 'pixel-density',
    label: 'Pixel Density',
    desc: 'Pixel grid density preset. Lower values improve performance; higher values increase detail',
    categoryId: 'performance',
    type: 'slider',
    defaultValue: PERFORMANCE_DEFAULTS.pixelDensity,
    range: { min: PIXEL_DENSITY_MIN, max: PIXEL_DENSITY_MAX, step: 1 },
    get: (api) => api.getPixelDensity(),
    set: (api, value) => api.setPixelDensity(value),
    disabledWhen: (api) =>
      typeof api.isPixelDensityLocked === 'function' &&
      api.isPixelDensityLocked(),
  },
  {
    id: 'effect-quality',
    label: 'Effect Quality',
    desc: 'Simulation quality, visual fidelity, and effect precision',
    categoryId: 'performance',
    type: 'slider',
    defaultValue: PERFORMANCE_DEFAULTS.effectQuality,
    range: { min: 0, max: 10, step: 1 },
    get: (api) => api.getEffectQuality(),
    set: (api, value) => api.setEffectQuality(value),
  },
  {
    id: 'frame-rate-target',
    label: 'Frame Rate Target',
    desc: 'Preferred frame rate for Pixel FS rendering',
    categoryId: 'performance',
    type: 'dropdown',
    defaultValue: PERFORMANCE_DEFAULTS.frameRateTarget,
    options: FRAME_RATE_OPTIONS.slice(),
    get: (api) => api.getFrameRateTarget(),
    set: (api, value) => api.setFrameRateTarget(value),
  },
  {
    id: 'adaptive-performance',
    label: 'Adaptive Performance',
    desc: 'Automatically ease expensive visuals when frame rate drops, then restore when performance recovers',
    categoryId: 'performance',
    type: 'toggle',
    defaultValue: PERFORMANCE_DEFAULTS.adaptivePerformance,
    get: (api) => api.getAdaptivePerformance(),
    set: (api, value) => api.setAdaptivePerformance(value),
  },
];

/**
 * Settings belonging to a category, optionally filtered by nested section
 * and/or active style.
 * @param {string} categoryId
 * @param {string} [activeStyleId]
 * @param {{ sectionId?: string | null }} [opts] — pass sectionId to scope to a
 *   nested section; pass `null` for category-root settings only (no sectionId)
 * @returns {SettingDef[]}
 */
export function getSettingsForCategory(categoryId, activeStyleId, opts) {
  const filterSection = opts && 'sectionId' in opts;
  return SETTINGS.filter((def) => {
    if (def.categoryId !== categoryId) return false;
    if (filterSection) {
      const want = opts.sectionId;
      if (want == null) {
        if (def.sectionId) return false;
      } else if (def.sectionId !== want) {
        return false;
      }
    }
    if (def.styleId && def.styleId !== activeStyleId) return false;
    return true;
  });
}

/**
 * Restore the complete factory-default Pixel FS configuration by loading the
 * Default preset through the Preset Manager — the single authoritative source
 * of truth for the default experience. No manual per-setting fallback; every
 * configurable field (color, mode, behavior, cursor, performance) is covered
 * by the preset snapshot.
 *
 * @param {object} api
 */
export function resetSettingsToDefaults(api) {
  if (typeof api.loadPreset === 'function') {
    api.loadPreset('default');
  }
}
