/* Declarative setting definitions — add entries here to grow the inspector.
   UI is generated by `js/settings/render.js`; do not hand-build rows for new controls. */

import { getStyleSegmentOptions } from './styles.js';

/**
 * @typedef {'segment' | 'rgb' | 'slider' | 'dropdown' | 'toggle' | 'button'} SettingType
 *
 * @typedef {object} SettingDef
 * @property {string} id
 * @property {string} label
 * @property {string} [desc]
 * @property {'global' | 'style'} category
 * @property {string} [styleId] — required when category === 'style'
 * @property {SettingType} type
 * @property {*} [defaultValue]
 * @property {Array<{ value: string, label: string, disabled?: boolean }>} [options]
 * @property {() => Array<{ value: string, label: string, disabled?: boolean }>} [optionsFrom]
 * @property {{ min: number, max: number, step?: number }} [range]
 * @property {boolean} [metaRow] — RGB swatch sits beside the label
 * @property {(api: object) => *} get
 * @property {(api: object, value: *, extra?: *) => void} set
 * @property {(api: object) => boolean} [disabledWhen]
 * @property {(api: object, selectable: string[]) => *} [resolveValue] — sync-time value coercion
 */

/** Global Pixel FS controls — always shown under Pixel FS. */
/** @type {SettingDef[]} */
export const PIXEL_FS_GLOBAL_SETTINGS = [
  {
    id: 'motion',
    label: 'Motion',
    desc: 'Animations and pixel field',
    category: 'global',
    type: 'segment',
    defaultValue: 'on',
    options: [
      { value: 'on', label: 'On' },
      { value: 'off', label: 'Off' },
    ],
    get: (api) => (api.getMotion() ? 'on' : 'off'),
    set: (api, value) => api.setMotion(value === 'on'),
  },
  {
    id: 'style',
    label: 'Style',
    desc: 'Pixel field style',
    category: 'global',
    type: 'segment',
    optionsFrom: getStyleSegmentOptions,
    get: (api) => api.getBgMode(),
    set: (api, value) => {
      if (!api.getMotion()) return;
      api.setBgMode(value);
    },
    disabledWhen: (api) => !api.getMotion(),
    resolveValue: (api, selectable) => {
      const mode = api.getBgMode();
      if (selectable.indexOf(mode) !== -1) return mode;
      return api.getLastImplementedBgMode();
    },
  },
  {
    id: 'global-color',
    label: 'Global Color',
    desc: 'Shared by Magnetic, Wave, and Lightning',
    category: 'global',
    type: 'rgb',
    defaultValue: { r: 255, g: 52, b: 158 },
    metaRow: true,
    get: (api) => api.getEffectColor(),
    set: (api, rgb, publish) => api.setEffectColor(rgb.r, rgb.g, rgb.b, publish),
  },
];

/**
 * Style-specific settings keyed by Pixel FS style id.
 * Add controls here when a style needs its own group; leave arrays empty for placeholder UI.
 *
 * @type {Record<string, SettingDef[]>}
 */
export const PIXEL_FS_STYLE_SETTINGS = {
  heat: [],
  wave: [],
  lightning: [],
  experimental: [],
};

/** Static inspector sections (non–style-specific). */
/** @type {Array<{ id: string, title: string, defaultOpen?: boolean, settings: SettingDef[] }>} */
export const STATIC_SECTIONS = [
  {
    id: 'pixel-fs',
    title: 'Pixel FS',
    defaultOpen: true,
    settings: PIXEL_FS_GLOBAL_SETTINGS,
  },
  {
    id: 'appearance',
    title: 'Appearance',
    defaultOpen: false,
    settings: [],
  },
  {
    id: 'layout',
    title: 'Layout',
    defaultOpen: false,
    settings: [],
  },
  {
    id: 'advanced',
    title: 'Advanced',
    defaultOpen: false,
    settings: [],
  },
];

export const STYLE_SETTINGS_SECTION = {
  id: 'style-settings',
  defaultOpen: true,
  emptyMessage: 'No style-specific settings available yet.',
};
